### ISSUE TITLE
ubuntu 20.04 support

### ISSUE THREAD

**Issue by dromer** [NVIDIA/ansible-role-nvidia-driver#25] opened 2020-11-18 14:49 UTC
What is exactly needed to "officially" support 20.04?

I ran the role on a 20.04 machine and superficially it seems fine.

**Comment by dpward** [comment] 2020-12-28 20:29
Duplicate of #15

**Comment by guenhter** [comment] 2022-07-21 05:04
I guess this can be closed

**Closed** 2022-07-22 11:11 UTC
